[package]
name = "doom_the_dark_ages"
version = "0.1.0"
edition = "2021"

[dependencies]
asr = { workspace = true, features = ["derive"] }
bytemuck = "1.23.1"
helpers = { path = "../helpers" }
idtech = { path = "../idtech" }
once_cell = "1.19.0"

[lib]
crate-type = ["cdylib"]
