[package]
name = "dismantled"
version = "0.1.0"
edition = "2021"

[dependencies]
asr = { workspace = true, features = ["derive"] }
helpers = { path = "../helpers" }
paste = "1.0.15"
zdoom = { path = "../zdoom" }

[lib]
crate-type = ["cdylib"]
